# Generated by Django 5.0.1 on 2024-01-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
