# Generated by Django 5.0.1 on 2024-01-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0002_rename_timestamp_message_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
